### ISSUE TITLE
View has - by default - a Body of type Never.

### ISSUE THREAD

**Issue by filip-sakel** [swiftwasm/Tokamak#110]
This introduces bugs and almost defeats the purpose of compile-time errors. To prevent the program compiling successfully without producing an error for a type like `Foo`:

```swift
struct Foo: View {
    
}
``` 

There are two options - that I can think of:

1. Add another _Never conditional conformances - to a dummy type like `_Never` that will require disambiguating when omitting the body:
    ```swift
    enum _Never: View {
        var body: Never { fatalError() }
    }

    extension View where Body == _Never {
        var body: _Never {
            fatalError("Can't access body of Never View.")
        }
    }
    ```
    That is a hack though and the error ("Type 'H' does not conform to protocol 'Block'") doesn't provide a fix possibly leaving a novice developer confused.

2. Remove the extension that provides an automatic conformance when Body is of type `Never` and move that behaviour to the ViewDeferredToRenderer protocol - or to an underlying view protocol such as _StuctureView, _View, _FatalView:

    ```swift
    protocol _StuctureView: View where Body == Never {}

    extension _StuctureView {
         var body: Never {
            fatalError("Can't access body of Structure View.")
        }
    }
    ```
    That IMO is the best option, as it avoids automatic type-inference altogether and provides a useful error message - that offers a fix.

**Comment by MaxDesiatov** [comment]
Thank you @filip-sakel, this is a great point, primarily because it also highlights the incompatibility with SwiftUI, it is now fixed in the `main` branch.
