### ISSUE TITLE
NavigationView/NavigationLink

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/Tokamak#129]
Having this view ready would clean up the demo page and make it easier to add or fix just one view. It’s probably good to start with the 2-column iPad style and maybe expand later on to an iPhone style on narrower viewports.

**Comment by MaxDesiatov** [comment]
This also could be a part of a bigger URL routing story, but for now just plain compatibility with SwiftUI should be enough to clean things up significantly.

**Comment by j-f1** [comment]
I did a quick test of a `NavigationView` with five subviews, and it renders:

- the first view in portrait on iPhones
- the fifth in landscape on iPhones (with the first view visible by tapping the back button or swiping in from the edge)
- the third view in portrait on iPads (with the first two views visible next to each other by swiping in from the edge or tapping the sidebar button)
- the second and third view in landscape on iPads (with the first view visible by swiping in from the edge or tapping the sidebar button)

(the fourth view is never visible)
Confusing!

**Comment by MaxDesiatov** [comment]
Is this with iOS 13 and Xcode 11.5, or iOS 14 and Xcode 12 betas?

**Comment by j-f1** [comment]
This is iOS 13 on iPhone and iOS 14 beta on iPad sim

**Comment by carson-katri** [comment]
My guess is that `NavigationView` only really expects 3 views. iPhone uses `StackNavigationViewStyle` by default, and iPad uses `DoubleColumnNavigationViewStyle`.
