### ISSUE TITLE
Logo for the project

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/Tokamak#132]
If you know of a suitable logo, or know anyone who could produce one, or can propose one yourself, please do. I've used stock images for the previous release with the React API, you can see them on [the Twitter profile](https://twitter.com/TokamakUI). If you're not familar with tokamaks, please use [the Wikipedia page](https://en.wikipedia.org/wiki/Tokamak) for inspirations. The whole idea was (and still is) to make a pun on React's atomic logo 😄

**Comment by j-f1** [comment]
From #131:

> I tried to do something with Blender but it just looked bad. My idea was to make the plasma donut in the middle be Swift orange and have some sort of containment device around it in blue that still lets you see the orange.

**Comment by MaxDesiatov** [comment]
I think the logo doesn't need to be too detailed, or at least we should have a very simplistic version for small sizes like `favico`, profile images etc. It could be something that reminds a plasma donut, but I'm not a designer to say something useful about that 🙈

**Comment by MaxDesiatov** [comment]
Also, one thing to consider is that the logo shouldn't probably reference SwiftUI in any way. As far as I know, both SwiftUI name and logo are trademarked and copyrighted, so we have to be careful no to infringe on any of that.

**Comment by carson-katri** [comment]
I designed something in Illustrator, should be simple enough for icons:

<img src="https://user-images.githubusercontent.com/13581484/86175650-bc76ac00-baf1-11ea-8d54-4e334fd80f24.png" width="150px" />

Here are orange variants to avoid SwiftUI trademark (if the gradient is included in that):
<img src="https://user-images.githubusercontent.com/13581484/86175656-be406f80-baf1-11ea-9c70-d22c8557cf53.png" width="150px" />
<img src="https://user-images.githubusercontent.com/13581484/86175692-cc8e8b80-baf1-11ea-9f77-9120c0ccdf4d.png" height="200px" />

It's supposed to resemble a ring like a Tokamak and Apple Park.

**Comment by MaxDesiatov** [comment]
The logo looks wicked (almost glowing!) in dark mode previews in VSCode, could you also add an outline to the title next to it in the last variant?

<img width="756" alt="Screenshot 2020-06-30 at 22 12 39" src="https://user-images.githubusercontent.com/112310/86177681-f6aa7280-bb1e-11ea-9fd1-de3a8c850388.png">

**Comment by carson-katri** [comment]
![LogoWithText@3x](https://user-images.githubusercontent.com/13581484/86178851-23e32a80-baf7-11ea-948c-c0cc7f2b789f.png)
I wish GitHub had an official dark mode 😞

**Comment by carson-katri** [comment]
![LogoWithText_1@3x](https://user-images.githubusercontent.com/13581484/86178932-49703400-baf7-11ea-8da2-3d804c8a3901.png)
I wish GitHub had an official dark mode 😞

**Comment by MaxDesiatov** [comment]
The iOS GitHub app supports dark mode by the way, here's how it looks there: ![image](https://user-images.githubusercontent.com/112310/86215970-3734db00-bb75-11ea-8aaf-4dff45d3cb55.jpeg)

**Comment by j-f1** [comment]
Seems like we have a logo!
