### ISSUE TITLE
Extend Path to match the SwiftUI API

### ISSUE THREAD

**Issue by carson-katri** [swiftwasm/Tokamak#156]
[This](https://github.com/quassummanus/SVG-to-SwiftUI) was just posted on the Swift subreddit. I wonder if the creator would be interesting in doing the reverse of that for TokamakDOM.

**Comment by MaxDesiatov** [comment]
The reverse would need to be a complete rewrite in Swift 🤔

**Comment by carson-katri** [comment]
Yeah, I guess it would be a lot of work to do that.
