### ISSUE TITLE
`Rectangle` frame is not being set properly

### ISSUE THREAD

**Issue by Outcue** [swiftwasm/Tokamak#185]
A simple rectangle example like this:

```
Rectangle()
    .background(Color.black)
    .frame(width: 100, height: 100)
```

is not rendering properly.

The width and height properties are being set properly on the div representing the rectangle, but the svg object that is a child of the rectangle div is not inheriting the width and height. The width and height of the svg div is 0, 0. 

If the width and height of the svg object are set, the rectangle will render properly.

**Comment by MaxDesiatov** [comment]
Thanks for reporting this @Outcue!

@carson-katri do you think that something like https://github.com/swiftwasm/Tokamak/issues/176 would help here? I imagine we could read width/height from the geometry proxy value and pass that to SVG?

**Comment by carson-katri** [comment]
Yeah, that could work.

Another solution would be to set the width and height of SVG to 100% if no size is specified.

**Comment by MaxDesiatov** [comment]
I imagine setting it to 100% by default also saves some cycles that would be spent on layout updates with `GeometryReader` 🤔

**Comment by carson-katri** [comment]
For reference, this is where the size of the SVG element is calculated: https://github.com/swiftwasm/Tokamak/blob/11af0f8d981ced3142f84e9ac1fa13e71c5ce0da/Sources/TokamakDOM/Shapes/Path.swift#L148
