### ISSUE TITLE
State vars have to be first

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/Tokamak#190]
If any non-state variables precede state variables, Tokamak crashes when the state variables are read.

Repro:

```swift
struct ThisView: View {
  let foo = 3
  @State var bar = 4

  @ViewBuilder var body: some View {
    Text("\(bar)")
  }
}
```

Encountered in #129.

This happens because `StackReconciler#render(compositeView:)` enumerates all the properties, resulting in it providing non-consecutive ids to `setupState`. A potential fix is to declare a `var stateIdx` outside of the loop and manually increment it when initializing each state variable.

https://github.com/swiftwasm/Tokamak/blob/ffa686c7dca8d454e88246ed2ba7106dee6c4836/Sources/TokamakCore/StackReconciler.swift#L115-L121

**Comment by MaxDesiatov** [comment]
The proposed fix seems totally legit, let me know if you're submitting a PR for it, otherwise I'll pick it up soon-ish.
