### ISSUE TITLE
`List` appearance changes when reloaded

### ISSUE THREAD

**Issue by Outcue** [swiftwasm/Tokamak#212]
If you run the Tokamak web demo (I am using Safari) and repeatedly click on the List item in the sidebar, the List will change appearance each time.

The first time, the list will appear with the proper styles applied.

The second time, the styling will vanish. Container groups and rounded corners will vanish.

The third time, the list will shrink in width.

After the third click, additional clicks will have no effect.

**Comment by MaxDesiatov** [comment]
This is no longer reproducible in `main`.
